Lab 2
sadikovaa/sadikovaa.github.io pull request #2
Opened 2022-10-03 08:14 UTC by sadikovaa

2022-10-03 12:51 UTC, BakasaRus requested changes
Сделать зачёркивания/подчёркивания/etc. и смену регистра символов

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/homework.html
> +    </style>
Лучше переделать вот так: https://www.w3schools.com/css/css_howto.asp

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/homework.html
> +  <header class="header-style">
Путает то, что один и тот же класс используется и у заголовков, и у шапки в целом. Надо бы для них разные классы написать, пусть и с одними стилями

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/styles.css
> +    font-family: "Century Gothic";
Надо подключить шрифт через Google Fonts

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/maths.html
> +            <img src="img/manul.jpg" align="left" height="320" class="image-radius">
`align` и `height` лучше вынести в класс

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/homework.html
> +      <input type="submit" class="type-3" value="Отправить">
На практике обычно оборачивают подписи полей и сами поля в `div`

2022-10-03 12:51 UTC, BakasaRus commented on WebTutor/styles.css
> +    background-color: #6FA8BD;
Что будет, если сюда закинуть не 6 символов, а 8?

2022-10-28 09:55 UTC, sadikovaa commented on WebTutor/styles.css
> +    background-color: #6FA8BD;
Последние 2 символа будут определять, насколько цвет будет прозрачным или непрозрачным

2022-10-31 12:33 UTC, BakasaRus commented on WebTutor/homework.html
> +      <input type="submit" class="type-3" value="Отправить">
Оборачивают каждое поле...

2022-10-31 12:33 UTC, BakasaRus approved these changes

2022-11-07 07:12 UTC, merged